version: '3.9'

services:
    wireguard:
        container_name: wireguard
        image: ghcr.io/wg-easy/wg-easy
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        ports:
            - 51820:51820/udp
            - 51821:51821/tcp
        expose:
            - 51820/udp
            - 51821/tcp
        environment:
            - LANG=en
            - WG_HOST=example.com
            - PASSWORD=1
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - wireguard:/etc/wireguard
volumes:
    wireguard:
